### ISSUE TITLE
Hide navigation bar while fullscreen on video

### ISSUE THREAD

**Issue by IStoleYourKidneys** [Frontesque/VueTube#152] opened 2022-03-21 16:03 UTC
![Screenshot_20220321-155506_VueTube](https://user-images.githubusercontent.com/102049584/159301545-0e68171c-cd31-4891-855b-f7725fae12cf.png)

**Comment by nokanol45** [comment] 2022-03-21 16:54
Seems to be related to #91 and #110

**Comment by Frontesque** [comment] 2022-03-22 00:46
duplicate of #110

**Closed by Frontesque** 2022-03-22 00:46 UTC
Labels: duplicate
