### ISSUE TITLE
Ut8 Turkish Character Problem

### ISSUE THREAD

**Issue by EmreKara5aya** [Frontesque/VueTube#62] opened 2022-03-16 11:55 UTC
**Describe the bug**
Turkish characters appear incorrectly in the application.  Example picture: Emre Belözoğlu 

**Screenshots**
![Screenshot_20220316_144550_com.Frontesque.youtube.jpg](https://user-images.githubusercontent.com/9382037/158584289-3c1e6052-65d8-40ae-8511-b7e70ae937e5.jpg)

**Device Information**
 -![Screenshot_20220316_145428_com.Frontesque.youtube.jpg](https://user-images.githubusercontent.com/9382037/158584464-4c367380-f5f7-4cdb-90d7-a9bba91f21f3.jpg)

**Comment by Frontesque** [comment] 2022-03-17 12:48
Try updating to the latest app build ([5743f1e](https://github.com/Frontesque/VueTube/commit/5743f1ef70c20780345b890ed3be4c907222f0c0)) is this still an issue?

**Comment by EmreKara5aya** [comment] 2022-03-18 11:18
Hi

The problem still persists

![Screenshot_20220318_141700_com.Frontesque.youtube.jpg](https://user-images.githubusercontent.com/9382037/158993828-f1f382b8-941a-4c48-9759-a45e5a853a08.jpg)

![Screenshot_20220318_141759_com.Frontesque.youtube.jpg](https://user-images.githubusercontent.com/9382037/158993871-ce85e5b2-d067-4ccb-b109-f8a1edfd3159.jpg)

**Comment by 404-Program-not-found** [comment] 2022-03-18 11:20
@EmreKara5aya we are aware of this issue. But most of the team is currently busy working on core features as of now, this problem will be fixed as soon as someone is available

**Comment by 404-Program-not-found** [comment] 2022-03-18 11:29
hm, that is really odd. It would appear that the app itself supports unicode, but search results don't. API error, perhaps?
![image](https://user-images.githubusercontent.com/56329333/158995294-894168c5-e895-41a1-b6e8-1d653e941c1c.png)

**Comment by DanWlker** [comment] 2022-03-19 16:51
![image](https://user-images.githubusercontent.com/60170554/159130072-4f46a671-9a20-46af-95f2-0fd32a96583e.png)

Well it's sort of fixed but not quite, the issue is the API returns result in the format of iso-8859-1 instead of utf-8, so a parse is required to convert it to utf-8 first. see:
https://stackoverflow.com/questions/34394537/node-js-json-parse-utf-8-issue

on vue.js or javascript this is done with unescape(encodeURIComponent(res)); see: 
https://stackoverflow.com/questions/5396560/how-do-i-convert-special-utf-8-chars-to-their-iso-8859-1-equivalent-using-javasc

**Comment by DanWlker** [comment] 2022-03-19 17:43
Nvm i thought it was an  ISO-8859-1 to UTF-8 conversion issue. On further inspection the bug, for Hangul it does not occur for me any more, for Turkish characters only some of the characters still have that issue.

**Comment by 404-Program-not-found** [comment] 2022-03-24 21:04
I'll take a look at what's happening

**Comment by 404-Program-not-found** [comment] 2022-03-26 08:26
fixed in #192. Closing issue

**Closed by 404-Program-not-found** 2022-03-26 08:26 UTC
Labels: bug, Priority: High

**Comment by KarstenPH** [comment] 2022-03-26 09:28
I should have probably added this earlier but it's too late and it has been fixed: Japanese hiragana characters seem to work (even with older build versions)
