### ISSUE TITLE
Cast to TV

### ISSUE THREAD

**Issue by Balthazar1234** [Frontesque/VueTube#258] opened 2022-04-21 14:23 UTC
Vanced was afaik the only (except for the original youtube) android app which included the option to connect with youtube running on a tv to control playback and select videos.
This possibility simplifies the handling of the TV considerably.

But as I understood the principle, the feature should not be confused with regular Chromecast

Newpipe is working on it for quite some time it seems although the code already exists.

**Comment by Frontesque** [comment] 2022-04-22 03:10
duplicate of #71

**Closed by Frontesque** 2022-04-22 03:10 UTC
